### ISSUE TITLE
LayerSwitcher and ZoomBox

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#10] opened 2012-12-17 08:06 UTC
When follow this steps: 
- Select ZoomBox
- Extent LayerSwitcher
- Click on a checkbox or radiobutton

Map makes a unwanted zoom.

**Comment by nachouve** [comment] 2012-12-18 11:58
This happens with other tools also (measurements).

**Comment by michogar** [comment] 2013-01-15 12:00
Don't happens to me. Works perfectly. Only when chooses measurement controls then appears Handler layer into LayerSwitcher like OpenLayers.Handler... Is this a bug with layer's name or with layerswitcher behaviour?

**Comment by jorgelf** [comment] 2013-05-02 14:38
Like @michogar, I can't reproduce it, although that problem happens sometimes when you click onto empty areas of the layer switcher, but I think that's completely acceptable as long as it works fine with the controls, and it does in my browser. I'm closing this, and the latter problem I described is a 'Won't fix' for me. If someone else experiences this problem, notify us.

**Closed as completed by jorgelf** 2013-05-02 14:38 UTC
Labels: bug, invalid
